name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update LLVM
        run: choco upgrade llvm -y

      - name: check clang
        run: clang-format --version

      - name: check clang-tidy
        run: clang-tidy --version

      - name: Configure CMake
        run: cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

#      - name: Test
#        run: cd ${{ env.BUILD_DIR }}/test/element && ctest -C ${{ env.BUILD_TYPE }} --output-on-failure

      - name: Run clang-format
        run: clang-format -i $(find -name "*.h" -not -path "./${{ env.BUILD_DIR }}/*" -or -name "*.cpp" -not -path "./${{ env.BUILD_DIR }}/*") --verbose -style=file
        shell: bash

      - name: Check clang-format
        run: git diff --exit-code

      - name: Run clang-tidy, src
        run: clang-tidy $(find ./src ./include -name "*.h" -not -path "./${{ env.BUILD_DIR }}/*" -or -name "*.cpp" -not -path "./${{ env.BUILD_DIR }}/*") --config-file=.clang-tidy -p ./${{ env.BUILD_DIR }} --header-filter=.* --warnings-as-errors=*
        shell: bash

      - name: Run clang-tidy, test
        run: clang-tidy $(find ./test -name "*.h" -not -path "./${{ env.BUILD_DIR }}/*" -or -name "*.cpp" -not -path "./${{ env.BUILD_DIR }}/*") --config-file=.clang-tidy-test -p ./${{ env.BUILD_DIR }} --header-filter=.* --warnings-as-errors=*
        shell: bash
