name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release
  BUILD_DIR: build

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: install ninja
        run: choco install ninja -y

      - name: verify ninja
        run: ninja --version

      - name: Configure CMake
        run: cmake -G Ninja -S . -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ env.BUILD_DIR }} --config ${{ env.BUILD_TYPE }}

      - name: Test
        run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure

      - name: Run clang-format
        run: clang-format -i $(find -name "*.h" -not -path "./${{ env.BUILD_DIR }}/*" -or -name "*.cpp" -not -path "./${{ env.BUILD_DIR }}/*") --verbose -style=file
        shell: bash

      - name: Check clang-format
        run: git diff --exit-code

      - name: Run clang-tidy
        run: clang-tidy $(find -name "*.h" -not -path "./${{ env.BUILD_DIR }}/*" -or -name "*.cpp" -not -path "./${{ env.BUILD_DIR }}/*") --config-file=.clang-tidy -p ./${{ env.BUILD_DIR }} --warnings-as-errors='*'
        shell: bash

